# Generated by Django 5.0.4 on 2024-09-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
