# Generated by Django 5.0.4 on 2024-05-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_item_expiry_date_item_image_alter_fridge_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
